config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  patch 'snippets/:id/flag', to: 'snippets#flag', as: 'snippet_flag'
  patch 'stories/:id/flag', to: 'stories#flag', as: 'story_flag'

  get '/snippets/:id/vine', to: 'snippets#vine', as: 'snippet_vine'
  resources :snippets, except: :create


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create', as: 'new_sign_up'

  patch '/upvote/:id', to: 'votes#upvote', as: 'vote_up'
  delete '/vote/:id', to: 'votes#destroy', as: 'vote_delete'

  resources :users, only: [:show, :edit, :update, :delete]

  get 'stories/search', to: 'stories#search', as: 'stories_search'


  resources :stories, except: :create

  get '/stories/:id/new', to: 'stories#new_nested_story', as: 'new_nested_story'
  post '/stories/:id/new', to: 'stories#create_nested_story', as: 'create_nested_story'

  resources :stories


  resources :tags
  get '/tags/:id/stories', to: 'tags#show', as: 'tags_show'

  resources :storytags

  root "welcome#index"

  get '/login', to: 'sessions#new'
  get '/dashboard', to: 'sessions#show', as: 'dashboard'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'




end

app/models/snippet.rb
class Snippet < ActiveRecord::Base

  include Flagging

  belongs_to :user

  has_many :stories
  has_many :flags, as: :flaggable

  validates_presence_of :content, :on => :update

  searchable do
    text :content
  end

  def self.most_recent
    Snippet.all.sort_by(&:created_at).reverse.take(5)
  end

  def self.all_most_recent
    Snippet.all.sort_by(&:created_at).reverse
  end

  def stories_count
    self.stories.count
  end

  def self.most_popular
    snippets = Snippet.all.sort_by(&:stories_count).reverse.take(5)
    snippets.map { |snippet| {snippet => snippet.stories_count} }
  end

    def self.all_most_popular
    snippets = Snippet.all.sort_by(&:stories_count).reverse
  end

  def self.random
    Snippet.all.shuffle
  end

  def remove_dangerous_html_tags!
    Sanitize.fragment(self, Sanitize::Config::RESTRICTED)
  end

  def tree
    # Hash[self.stories.to_a.group_by{|s| s.parent_id}.map{|k,v| [(if k then k else 0 end), v] }]
  end

  def children
    self.stories.where(parent_id: nil)
  end

  def as_json(options={})
    { id: id,
      type: "snippets",
      published: true,
      content: content,
      children: self.children }
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def index
    @snippets = Snippet.random
    @most_popular = Snippet.all_most_popular
    @most_recent = Snippet.all_most_recent
  end

  def new
    p params
    @snippet = Snippet.create
  end


  def update
    @snippet = Snippet.find(params["id"])
    snippet_content = Sanitize.fragment(params["snippet"]["content"], Sanitize::Config::BASIC)
    if @snippet.update(content: snippet_content)
      User.find(session[:user_id]).snippets << @snippet
      if request.xhr?
        render plain: "Autosaved on " + @snippet.updated_at.strftime("%m/%d/%Y at %I:%M:%S %p")
      else
        redirect_to snippet_path(@snippet)
      end
    else
      if request.xhr?
        render plain: "Failed to autosave: #{@snippet.errors.messages.inspect}"
      else
        flash[:notice] = "There was an error saving your snippet. Please make sure it isn't blank."
        render :new
      end
    end
  end

  def show
    set_snippet.remove_dangerous_html_tags!
    @stories = @snippet.stories.where(published: true)
  end

  def destroy
    @snippet = Snippet.find(params["id"])
    @snippet.destroy
    redirect_to "/"
  end

  def flag
    @snippet = Snippet.find(params[:id])
    Flag.create(flaggable_type: "Snippet", flaggable_id: @snippet.id)
    flash[:notice] = "Thank you. We'll look into this shortly."
    redirect_to snippet_path(@snippet.id)
  end

  def vine
    @snippet = Snippet.find(params[:id])
    # @snippet.remove_dangerous_html_tags
    render layout: false
  end



  private

    def set_user
      params[:snippet][:user_id] = session[:user_id]
    end

    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    def snippet_params
      set_user
      params.require(:snippet).permit(:user_id, :content)
    end

end

app/views/snippets/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="snippet-header">
      Snippets
    </div>
    <ul class="tabs" data-tab>
      <li>Sort By:</li>
      <li class="tab-title active"><a href="#panel1">All</a></li>
      <li class="tab-title"><a href="#panel2">Most Recent</a></li>
      <li class="tab-title"><a href="#panel3">Most Popular</a></li>
    </ul>
    <div class="tabs-content">
      <div class="content active" id="panel1">
        <% @snippets.each do |snippet| %>
            <% if snippet.content %>
            <div class="snippet">
              <div class="snippet-content">
                <%= strip_tags(snippet.content) %>
              </div>
              <div class="snippet-link">
                <%= link_to "(link)", snippet_path(snippet) %>
              </div>
            </div>
            <% end %>
            <% end %>
      </div>
      <div class="content" id="panel2">
        <% @most_recent.each do |snippet| %>
            <% if snippet.content %>
            <div class="snippet">
              <div class="snippet-content">
                <%= strip_tags(snippet.content) %>
                <p> Submitted on <%= snippet.created_at.to_date %></p>
              </div>
              <div class="snippet-link">
                <%= link_to "(link)", snippet_path(snippet) %>
              </div>
            </div>
            <% end %>
            <% end %>
      </div>
      <div class="content" id="panel3">
        <% @most_popular.each do |snippet| %>
            <% if snippet.content %>
            <div class="snippet">
              <div class="snippet-content">
                <%= strip_tags(snippet.content) %>
                <p> Stories: <%= snippet.stories_count %></p>
              </div>
              <div class="snippet-link">
                <%= link_to "(link)", snippet_path(snippet) %>
              </div>
            </div>
            <% end %>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/snippets/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="new-snippet">
      Submit a Snippet
    </div>
      <%= form_for(@snippet) do |f| %>
        <%= f.text_area :content, placeholder: "Content goes here...", :class => "redactor"%>
        <%= f.submit 'Submit', :id => 'submit_new_content', class: "button round secondary small"%>
      <% end %>
    <%= link_to 'Cancel', root_path, data: { confirm: 'Are you sure?' }, class: "button round secondary small" %>
    <div class="autosave">

    </div>
  </div>
</div>

app/views/snippets/show.html.erb
<div class="row">
  <div class="large-12 columns">


    <div class="snippet">
      <div class="snippet-content">
        <%= @snippet.content.html_safe %>
        <p> Submitted on <%= @snippet.created_at.to_date %></p>
      </div>
      <div class="snippet-author">
        <% if @snippet.user %>
        - <%= link_to @snippet.user.username, user_path(@snippet.user)  %>
        <% end %>
      </div>
    </div>


    <%= link_to snippet_vine_path(@snippet) do %>
    <div id="vine-hover"></div>
    <% end %>

    <div class="submit-story">
      <ul>
        <% if current_user %>
        <li><%=link_to "Submit a story for this snippet", new_story_path(snippet_id: @snippet.id), class: "button round snippet-button" %></li>
        <%= form_for @snippet, :url => snippet_flag_path(@snippet) do |f| %>
        <li><%= f.submit "Report inappropriate", class: "button round snippet-button small" %></li>
        <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="snippet-stories">
    <div class="snippet-stories-header">
      Stories for this snippet:
    </div>
    <% if @stories.count != 0 %>
    <% @stories.each do |story| %>
    <div class="snippet-story">
      <%= link_to story.title, story_path(story) %>
    </div>
    <% end %>
    <% else %>
    <p class="center-text">There are currently no stories for this snippet.<p>
      <% if current_user == nil %>
      <p class="center-text"><a href="#" data-reveal-id="signup">Inspired? How about signing up!</a></p>
      <% end %>
      <% end %>
    </div>
  </div>

  <div id="signup" class="reveal-modal" data-reveal>
    <%= render 'layouts/signup' %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
</div>

app/views/snippets/vine.html.erb
  <html>

  <head>
    <%= javascript_tag do %>
    window.rootJSON = <%= raw @snippet.to_json(include: :children) %>
    <% end %>
    <link href="http://fonts.googleapis.com/css?family=Bitter|Bree+Serif" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="/assets/joint.js?body=1"></script>
    <script src="/assets/vine.js?body=1"></script>
    <link rel="stylesheet" media="screen" href="/assets/joint.css?body=1">
    <link rel="stylesheet" media="screen" href="/assets/foundation_and_overrides.css?body=1">
    <style>
    body {
      font-family: 'Bitter';
      background-color: #FCFDFF;
    }

    #vine-graph {
      width: 100%;
      height: 100%;
    }

.top-bar-section > ul > .divider, .top-bar-section > ul > [role="separator"] {
  padding-right: 5px;
  border-right: 1px solid transparent;
}

.top-bar-section li:not(.has-form) a:not(.button) {
  font-family: 'Bitter', serif;
  font-size: 1em;
  background: none;
  color: #008CBA;
}

.top-bar-section ul li {
  background: none;
}

.top-bar-section .dropdown li:not(.has-form):not(.active) > a:not(.button) {
  background: none;
}

.top-bar-section li:not(.has-form) a:not(.button):hover {
}

.top-bar-section .dropdown li:not(.has-form):not(.active) > a:not(.button) {
  background-color: #372e27;
}

.sticky {
  padding: 10px;
  border-bottom: 2px solid #372e27;
}

.top-bar {
  padding-bottom: 20px;
  margin: 10px;
  background: none;
  border-bottom: 2px solid #372e27;
}
.top-logo-name a {
  padding: 5px 10px 15px 10px;
  font-size: 1.8em;
}

    </style>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="top-logo-name">
          <% if current_user %>
            <%= link_to 'Story Vine', :dashboard, class: "story-vine-link" %>
          <% else %>
            <%= link_to 'Story Vine', :root, class: "story-vine-link" %>
          <% end %>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="divider"></li>
            <li> <%= link_to 'Back', :back %></li>
            <li class="divider"></li>
        </ul>

      </section>
    </nav>


  <div id="vine-graph">

  </div>

  </body>
  </html>