config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  patch 'snippets/:id/flag', to: 'snippets#flag', as: 'snippet_flag'
  patch 'stories/:id/flag', to: 'stories#flag', as: 'story_flag'

  get '/snippets/:id/vine', to: 'snippets#vine', as: 'snippet_vine'
  resources :snippets, except: :create


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create', as: 'new_sign_up'

  patch '/upvote/:id', to: 'votes#upvote', as: 'vote_up'
  delete '/vote/:id', to: 'votes#destroy', as: 'vote_delete'

  resources :users, only: [:show, :edit, :update, :delete]

  get 'stories/search', to: 'stories#search', as: 'stories_search'


  resources :stories, except: :create

  get '/stories/:id/new', to: 'stories#new_nested_story', as: 'new_nested_story'
  post '/stories/:id/new', to: 'stories#create_nested_story', as: 'create_nested_story'

  resources :stories


  resources :tags
  get '/tags/:id/stories', to: 'tags#show', as: 'tags_show'

  resources :storytags

  root "welcome#index"

  get '/login', to: 'sessions#new'
  get '/dashboard', to: 'sessions#show', as: 'dashboard'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'




end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :snippets
  has_many :stories, foreign_key: :author_id
  has_many :votes
  has_many :flags, as: :flaggable

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def all_published
    self.stories.select do |story|
      story.published
    end
  end

  def all_unpublished
    self.stories.select do |story|
      story.published == false
    end
  end

  # def award_badge
  #   if self.stories.count == 1
  #     @badge = Badge.create(title:"First Story Written", story_id: )
  #     return @badge.title
  #   end
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      redirect_to :back
      flash[:notice] = "There was an error with your signup."
    end
  end

  def new
  end

  def edit
    if @user.id == session[:user_id]
      render :edit
    else
      redirect_to :root
    end
  end

  def show
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(session[:user_id])
    if @user.update(user_params)
      render :show
    else
     @errors = @user.errors.messages
     redirect_to :back
    end
  end

  def destroy
  end

  private

  def set_user
    @user = User.find(params[:id])

  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :first_name, :last_name, :email, :pic_url, :url, :bio, :country)
  end


end

app/views/users/edit.html.erb
<div class="center row">
   <link href='http://fonts.googleapis.com/css?family=Bitter|Bree+Serif' rel='stylesheet' type='text/css'>
  <div class="section-container tabs" data-section="tabs">
  <section class="active">
  <div class="large-12 columns">

<div id="edit_user_form">
  <%= form_for(@user) do |f| %>
  <fieldset>
    <legend>This is You!</legend>
  <p>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

   <%= f.label :last_name %>
   <%= f.text_field :last_name %>
   <%= f.label :email %>
   <%= f.text_field :email %>
   <%= f.label :pic_url%>
   <%= f.text_field :pic_url %>
   <%= f.label :url %>
   <%= f.text_field :url %>
   <%= f.label :country %>
   <%= f.text_field :country %>
   <%= f.label :bio %>
   <%= f.text_area :bio, rows: 10 %>
 </p>
   <%= f.submit "Update",:class => "button expand" %>
  </fieldset>
  <% end %>
  </div>
</div>
</section>
</div>
</div>

app/views/users/index.html.erb
<div class="all-users">
  <% @users.each do |user| %>
    <%= link_to "#{user.username}", user_path(user) %><br>
    <% user.badges.each do |badge| %>
      <%= badge.title  %>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
   <div class="large-12 columns">
      <div id="sign_up_form">
  <%= form_for(:user, url: new_sign_up_path) do |f| %>
   <%= f.label :username %>
   <%= f.text_field :username %>
   <%= f.label :password %>
   <%= f.password_field :password %>
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation %>
   <%= f.label :first_name %>
   <%= f.text_field :first_name %>
   <%= f.label :last_name %>
   <%= f.text_field :last_name %>
   <%= f.label :email %>
   <%= f.text_field :email %>
   <%= f.label :pic_url%>
   <%= f.text_field :pic_url %>
   <%= f.label :url %>
   <%= f.text_field :url %>
   <%= f.label :country %>
   <%= f.text_field :country %>
   <%= f.label :bio %>
   <%= f.text_area :bio %>
   <%= f.submit "Sign Up" %>
  <% end %>
</div>
</div></div>

app/views/users/show.html.erb
<div class="row dashboard-fullWidth">
  <div class="large-12 columns">
    <div id="profile-page">
      <h1><%= @user.username.capitalize %>'s Profile</h1>
      <div class="row">
       <div class="large-2 columns">
         <div class="circular"><%= image_tag @user.pic_url %></div>
       </div>
       <div class="large-10 columns">
         <div class="row">
          <div class="large-3 columns">
            <div class="user-info-profile-page">
              <h4 class="user-info">Username:</h4><%= @user.username %>
              <h4 class="user-info">Country:</h4><%= @user.country %>
              <h4 class="user-info">Name:</h4> <%= @user.first_name %>
              <h4 class="user-info"> URL:</h4><%= link_to "Website", @user.url %>
            </div>
          </div>
          <div class="large-9 columns">
            <div class="user-info-profile-page">
              <h4 class="user-info">Bio:</h4><%= @user.bio %>
              <% if session[:user_id] == @user.id %>
              <p style="margin-top: 10%; width: 55%" align="right">
                <%=link_to "Edit Profile", edit_user_path(current_user), class: "button radius small" %>
              </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row dashboard-fullWidth">
      <div class="large-12 columns">
    <h4 class="user-info-content">User's Snippets</h4>
    <% if @user.snippets %>
      <ul>
        <% @user.snippets.each do |snippet| %>
        <li><%= link_to strip_tags(snippet.content), snippet_path(snippet) %></li>
        <% end %>
      </ul>
    <% else %>
      This user has no snippets.
    <% end %>
     <h4 class="user-info">User's Stories</h4>
     <% if @user.all_published %>
     <ul>
       <% @user.all_published.each do |story| %>
        <li><%= link_to strip_tags(story.title), story_path(story) %></li>
       <% end %>
     </ul>
      <% else %>
        This user has no published stories.
      <% end %>
  </div>
</div>


  </div>





  <div class="users-badges">
    <h4><%# @user.username.capitalize %></h4>
    <%# @user.stories.each do |story|  %>
    <%# story.badges.each do |badge| %>
    <%# badge.title %>
    <%# end %>
    <%# end %>
  </div>


</div>
</div>