config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  patch 'snippets/:id/flag', to: 'snippets#flag', as: 'snippet_flag'
  patch 'stories/:id/flag', to: 'stories#flag', as: 'story_flag'

  get '/snippets/:id/vine', to: 'snippets#vine', as: 'snippet_vine'
  resources :snippets, except: :create


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create', as: 'new_sign_up'

  patch '/upvote/:id', to: 'votes#upvote', as: 'vote_up'
  delete '/vote/:id', to: 'votes#destroy', as: 'vote_delete'

  resources :users, only: [:show, :edit, :update, :delete]

  get 'stories/search', to: 'stories#search', as: 'stories_search'


  resources :stories, except: :create

  get '/stories/:id/new', to: 'stories#new_nested_story', as: 'new_nested_story'
  post '/stories/:id/new', to: 'stories#create_nested_story', as: 'create_nested_story'

  resources :stories


  resources :tags
  get '/tags/:id/stories', to: 'tags#show', as: 'tags_show'

  resources :storytags

  root "welcome#index"

  get '/login', to: 'sessions#new'
  get '/dashboard', to: 'sessions#show', as: 'dashboard'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'




end

app/models/story.rb
class Story < ActiveRecord::Base

  include Flagging

  belongs_to :author, class_name: "User"
  belongs_to :parent, class_name: "Story"
  belongs_to :snippet

  has_many :story_tags
  has_many :tags, through: :story_tags
  has_many :votes
  has_many :children, class_name: "Story", foreign_key: :parent_id

  has_many :flags, as: :flaggable

  has_many :badges


  validates_presence_of :title, :on => :update
  validates_presence_of :content, :on => :update

  searchable do
    text :title, :boost => 5.0
    text :content
  end

  def self.published
    Story.all.where(published: true).shuffle
  end

  def vote_count
    self.votes.where(liked: true).count
  end

  def self.most_popular
    stories = Story.all.where(published: true).sort_by(&:vote_count).reverse.take(5)
    stories.map { |story| {story => story.vote_count} }
  end

  def self.all_most_popular
    Story.all.where(published: true).sort_by(&:vote_count).reverse
  end

   def self.all_most_recent
    Story.all.where(published: true).sort_by(&:created_at).reverse
  end

  def self.most_recent
    Story.all.where(published: true).sort_by(&:created_at).reverse.take(5)
  end

  def award_badge
    has_a_first_story_badge = false
    self.badges.each do |badge|
      has_a_first_story_badge = true if badge.title = "First Story Written"
    end
    return "First Story Written" if has_a_first_story_badge
    if !has_a_first_story_badge
      badge = Badge.create(title: "First Story Written", story_id: self.id)
      self.badges << badge
      return badge.title
    end
  end

  def most_voted
    current_stories = Story.all.sort_by {|story| story.votes.count }
    if self.votes.count > current_stories.last.votes.count
      badge = Badge.create(title: "Most Voted", story_id: self.id)
      return badge.title
    end
  end

  def remove_dangerous_html_tags!
    Sanitize.fragment(self, Sanitize::Config::RESTRICTED)
  end

  def as_json(options={})
    { id: id,
      type: "stories",
      published: published,
      title: title,
      children: self.children }
  end

  def self.random_story
    Story.published.first
  end


end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :destroy, :update, :new_nested_story, :create_nested_story]
  # before_action :child_story_params, only: [:new_nested_story, :create_nested_story]

  def index
    @stories = Story.published
    @most_popular = Story.all_most_popular
    @most_recent = Story.all_most_recent
  end

  def search
    @search = Story.search do
      if params[:search].nil? || params[:search].empty?
        stext = ''
      else
        stext = params[:search]
      end
      fulltext stext, :highlight => true
    end

    @snip_search = Snippet.search do
      if params[:search].nil? || params[:search].empty?
        stext = ''
      else
        stext = params[:search]
      end
      fulltext stext, :highlight => true
    end

    @searched_snippets = @snip_search.results
    @searched_stories = @search.results
  end

  def show
    find_vote(@story)
    @story.remove_dangerous_html_tags!
    @snippet = @story.snippet
    @tags = Tag.tags_for_select
    # show particular story
  end

  def new
    @story = Story.create(snippet_id: params[:snippet_id])
  end


  def create
    # create new story
    @story = Story.new(story_params)
    if @story.save
      redirect_to story_path(@story)
    else
      render :new
    end
  end


  def edit
    @story.remove_dangerous_html_tags!
  end

  def update
    @story = Story.find(params["id"])
    story_content = Sanitize.fragment(params["story"]["content"], Sanitize::Config::BASIC)
    if @story.update(content: story_content, title: params["story"]["title"], published: params["story"]["published"])
      User.find(session[:user_id]).stories << @story
      if request.xhr?
        render plain: "Autosaved on " + @story.updated_at.strftime("%m/%d/%Y at %I:%M:%S %p")
      else
        redirect_to story_path(@story)
      end
    else
      if request.xhr?
        render plain: "Failed to autosave: #{@story.errors.messages.inspect}"
      else
        flash[:notice] = "There was an error saving your story. Please make sure the fields aren't blank."
        render :new
      end
    end
  end

  def destroy
    @story.destroy
    redirect_to root_path
  end


  def flag
    @story = Story.find(params[:id])
    Flag.create(flaggable_type: "Story", flaggable_id: @story.id)
    flash[:notice] = "Thank you. We'll look into this shortly."
    redirect_to story_path(@story.id)
  end

  def new_nested_story
    @story_new = Story.new
    # render :create_nested_story
  end

  def create_nested_story
     @story_new = Story.new(title: params[:title], author_id: params[:session_id], parent_id: set_story.id, snippet_id: params[:story][:snippet_id])
    if @story_new.save
      @parent = set_story
      @parent.children << @story_new
      redirect_to story_path(@story_new)
    else
      render :new
      # this should give errors
      # redirect_to login_path
    end
  end

  private

  def find_vote(story)
    @vote = story.votes.find_by(user_id: session[:user_id], story_id: story.id )
  end

  def set_story
    @story = Story.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:title, :content, :snippet_id, :author_id, :published, :parent_id)
  end

  # def child_story_params
  #   @new_story = Story.find(params[:new_story].id)
  # end


end

app/views/stories/edit.html.erb
<div class="row">
  <div class="large-12 columns">
<h1>Edit Your Story</h1>

  <%= form_for @story do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %><br>

    <%= f.label :content %>
    <%= f.text_area :content, :value => @story.content.html_safe, class: "redactor" %><br>

    Would you like to publish this story?
    <%= f.radio_button :published, false, { :checked => true } %> No
    <%= f.radio_button :published, true %> Yes

    <%= f.submit %>

  <% end %>
<div id="publish-warning">
  Are you sure? This story will no longer be editable.
</div>
</div></div>

app/views/stories/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="snippet-header">Stories</div>
    <ul class="tabs" data-tab>
      <li>Sort By:</li>
      <li class="tab-title active"><a href="#panel1">All</a></li>
      <li class="tab-title"><a href="#panel2">Most Recent</a></li>
      <li class="tab-title"><a href="#panel3">Most Popular</a></li>
    </ul>
    <div class="tabs-content">
      <div class="content active" id="panel1">
        <% @stories.each do |story| %>
        <div class="snippet">
          <div class="story-content">
            <h4><%= link_to story.title, story_path(story) %></h4>
            <p>Written By: <%= link_to "#{story.author.username}", user_path(story.author) %></p>
          </div>
        </div>
        <% end %>
      </div>
      <div class="content" id="panel2">
        <% @most_recent.each do |story| %>
        <div class="snippet">
          <div class="story-content">
            <h4><%= link_to story.title, story_path(story) %></h4>
            <p>Written By: <%= link_to "#{story.author.username}", user_path(story.author) %></p>
            Published on <%= story.created_at.to_date %>
          </div>
        </div>
        <% end %>
      </div>
      <div class="content" id="panel3">
        <% @most_popular.each do |story| %>
        <div class="snippet">
          <div class="story-content">
            <h4><%= link_to story.title, story_path(story) %></h4>
            <p>Written By: <%= link_to "#{story.author.username}", user_path(story.author) %></p>
            Votes: <%= story.vote_count %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/stories/new.html.erb
<div id="container" class="new-story-page">
  <div class="row">
    <div class="large-12 columns">

      <div class="snippet">
        <div class="snippet-content">
        <h4>Snippet:</h4>
           <%= strip_tags(@story.snippet.content) %>
        </div>
        <div class="snippet-author">
          <% if @story.snippet.user %>
            <%= link_to @story.snippet.user.username, user_path(@story.snippet.user)  %> (<%= link_to "link", @story.snippet %>)
          <% end %>
        </div>
      </div>


      <h1> Create a new story </h1>
        <%= form_for @story do |f| %>
          <%= f.label :title %>
          <%= f.text_field :title %><br>

          <%= f.label :content %>
          <%= f.text_area :content, :class => "redactor"%><br>
          <%= f.hidden_field :published, :value => false %>
          <%= f.submit "Save", class:"button round" %>
        <% end %>
        <div class="autosave">
        </div>

      </div>
    </div>
</div>

app/views/stories/new_nested_story.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="snippet">
    <div class="root-snippet">
    <h3>Snippet</h3>
      <%= strip_tags(@story.snippet.content) %>
    </div>
  </div>

    <br><br>

    <div class="parent-accordion-bar">
      <ul class="accordion" data-accordion>
        <li class="accordion-navigation">
          <a href="#panel1a">Parent Story</a>
            <div id="panel1a" class="content active">
              <%= link_to "#{@story.title}", story_path(@story) %>
            </div>
        </li>
      </ul>
    </div>

    <br><br>

    <h1> Create a new story </h1>
    <%# params %>
    <%= form_for @story_new do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %><br>
      <%= f.hidden_field :parent_id, :value => @story.id %>
      <%= f.hidden_field :snippet_id, :value => @story.snippet.id %>
      <%= f.hidden_field :author_id, :value => current_user.id %>
      <%= f.label :content %>
      <%= f.text_area :content, :class => "redactor"%><br>
      <%= f.hidden_field :published, :value => false %>

      <%= f.submit "Save", class: "button round snippet-button small" %>
    <% end %>
    <div class="autosave">

    </div>



  <div class="story-show">
      <ul class="side-nav-1">
        <h4>Other Stories Written Off Of "<%= @story.title %>"</h4>
          <% @story.children.each do |story| %>
            <p><%= link_to "#{story.title}", story_path(story) %></p>
          <% end %>
      </ul>
  </div>


  </div>
</div>

<br><br>

app/views/stories/search.html.erb
<div class="row">
  <div class="large-vine columns">
    <div id="search-results">
      <% if (@searched_stories + @searched_snippets).empty? %>
        <br>
        <h3> We couldn't find any content containing "<%= params[:search] %>".</h3>
      <% elsif !@searched_stories.empty? %>

        <div class="dashboard-header"> Stories with "<%= params[:search] %> in the title": </div>
        <% @searched_stories.each do |story| %>
          <% display_string = story.title.downcase %>
          <% x = params[:search].downcase %>
          <% if display_string.include?(params[:search].downcase) %>
            <% display_string.sub!(params[:search].downcase, "<mark><strong>#{x}</strong></mark>" ) %>
            <br>
            <li><%= link_to display_string.html_safe, story_path(story) %></li>
          <% end %>
        <% end %>


        <div class="dashboard-header"> Stories that mention "<%= params[:search] %>": </div>
          <% @searched_stories.each do |story| %>
            <% if story.content.downcase.include?(params[:search].downcase) %>
              <li><%= link_to story.title, story_path(story) %></li>
            <% end %>
          <% end %>
      <% end %>

      <% if !@searched_snippets.empty? %>
        <br>
        <div class="dashboard-header">Snippets that contain"<%= params[:search] %>":</div>
        <% @searched_snippets.each do |snip| %>
          <% display_string = snip.content.downcase %>
          <% x = params[:search].downcase %>
          <% if display_string.include?(params[:search].downcase) %>
            <% display_string.sub!(params[:search].downcase, "<mark><strong>#{x}</strong></mark>" ) %>
            <li><%= link_to display_string.html_safe, snippet_path(snip) %></li>
          <% end %>
        <% end %>
      <% end %>

      </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="row">
  <div class="large-12 columns">

    <div class="snippet story-snippet-show">
      <div class="snippet-content">
      <h4>Snippet:</h4>
         <%= strip_tags(@snippet.content) %>
      </div>
      <div class="snippet-author">
        <% if @story.snippet.user %>
          <%= link_to @story.snippet.user.username, user_path(@story.snippet.user)  %> (<%= link_to "link", @story.snippet %>)
        <% end %>
      </div>
    </div>

    <div class="parent-story">
      <% if @story.parent != nil %>
        <div class="story-show">
          <h4>This story was written off:</h4>
            <%= link_to "#{@story.parent.title}", story_path(@story.parent.id) %><br>
        </div>
      <% end %>
    </div>

    <div class="story-show">
      <% if @story.title && @story.content %>
        <h4><%= @story.title.html_safe %></h4>
        <%= @story.content.html_safe %>

        <div class="line-separator"></div><br><br>

        Written By: <%= link_to "#{@story.author.username}", user_path(@story.author.id) %><br></br>
        <% if @story.published && session[:user_id] %>
          Like this story? <%= link_to "Write Off Of This Story", new_nested_story_path %>
          <% elsif !current_user %>
          <p class="center-text"><a href="#" data-reveal-id="signup">Inspired? How about signing up!</a></p>
        <% end %>
      <% end %>


      <% if story_editable?(@story) %>
      <div>
        <% if !@story.published && story_editable?(@story) %>
          <%= link_to "Edit", edit_story_path(@story) %><br>
          <%= link_to "Delete", @story, :method => :delete %>
        <% end %>

      </div>


      <% if current_user %>
        <%= form_for @story, :url => story_flag_path(@story) do |f| %>
        <%= f.submit "Report inappropriate", class:"button round report" %>
        <% end %>
      <% end %>



      <div class="story-tags">
        <h4>Tags</h4>
        <% @story.tags.each do |tag| %>
          <%= link_to "#{tag.name}", tags_show_path(tag) %><br>
        <% end %>
        <%= render :partial => 'tags/tagform'%>
      </div>
      <% end %>

  <div class="vine-for-story">
   <%= link_to snippet_vine_path(@story.snippet) do %>
        <div id="vine-hover"></div>
      <% end %>
    </div>

    <div class="vine-icon">
      Trace The History
  </div>

      <div class="row">
        <div class="small-11 small-centered columns">
      <div class="vote-count">
        Votes: <%= @story.vote_count %>
      </div>
      </div>
    </div>

          <div class="row">
    <div class="small-11 small-centered columns">
      <div class="vote-button" id="vote-center-button">
        <% if current_user %>
          <div id="upvote">
          <% if @vote != nil && @vote.user_id == current_user.id %>
            <%= button_to "Downvote",vote_delete_path(@vote), :method => :delete, :class => "button round", :confirm => "Are you sure ?", id: "voterguy" %>
          <% else %>
            <%= render "votes/new" %>
          <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

    </div>


    <div class="story-children">
      <div class="story-show">
        <h4>Children Stories:</h4>
        <% @story.children.each do |story| %>
          <% if story.published %>
            <p><%= link_to "#{story.title}", story_path(story.id) %><br>
            By: <%= story.author.username %></p>
          <% end %>
        <% end %>
      </div>
    </div>




  </div>
</div>