config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  patch 'snippets/:id/flag', to: 'snippets#flag', as: 'snippet_flag'
  patch 'stories/:id/flag', to: 'stories#flag', as: 'story_flag'

  get '/snippets/:id/vine', to: 'snippets#vine', as: 'snippet_vine'
  resources :snippets, except: :create


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create', as: 'new_sign_up'

  patch '/upvote/:id', to: 'votes#upvote', as: 'vote_up'
  delete '/vote/:id', to: 'votes#destroy', as: 'vote_delete'

  resources :users, only: [:show, :edit, :update, :delete]

  get 'stories/search', to: 'stories#search', as: 'stories_search'


  resources :stories, except: :create

  get '/stories/:id/new', to: 'stories#new_nested_story', as: 'new_nested_story'
  post '/stories/:id/new', to: 'stories#create_nested_story', as: 'create_nested_story'

  resources :stories


  resources :tags
  get '/tags/:id/stories', to: 'tags#show', as: 'tags_show'

  resources :storytags

  root "welcome#index"

  get '/login', to: 'sessions#new'
  get '/dashboard', to: 'sessions#show', as: 'dashboard'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'




end

app/views/layouts/_featured.html.erb
<h3>Featured Story</h3>

app/views/layouts/_flaggedposts.html.erb
FLAGGED STORIES
<% @flagged_stories.each do |story| %>
<%= link_to story.title, story_path(story) %>
<% end %>


FLAGGED SNIPPETS
<% @flagged_snippets.each do |snippet| %>
<%= link_to snippet.content, snippet_path(snippet) %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="row fullWidth">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Story Vine 2015</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">

      <li class="divider"></li>

        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_login.html.erb
  <%= form_for(:session, url: login_path) do |f| %><br>
  <fieldset>
    <legend>Login</legend>
    <%= f.text_field :email, :placeholder => "Email" %>
    <%= f.password_field :password, :placeholder => "Password"%>
    <%= f.submit "Login", :class => "button secondary expand" %>
  <% end %>
</fieldset>
<a href="#" data-reveal-id="signup">New User? Signup!</a>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="top-logo-name">
      <% if current_user %>
      <%= link_to 'Story Vine', :dashboard, class: "story-vine-link" %>
      <% else %>
      <%= link_to 'Story Vine', :root, class: "story-vine-link" %>
      <% end %>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to 'Browse Snippets', snippets_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Browse Stories', stories_path %></li>
      <li class="divider"></li>

      <li><a href="#" data-dropdown="search-form">Search</a></li>
      <li class="divider"></li>
      <% if current_user %>
      <li><%= link_to "#{current_user.username.capitalize}", user_path(current_user) %></li>
      <li class="divider"></li>
      <li class="has-dropdown">
        <a href="#">MENU</a>
        <ul class="dropdown">
          <li class="divider"></li>
          <li><%= link_to 'New Snippet', new_snippet_path%></li>
          <li class="divider"></li>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to 'Dashboard', dashboard_path %></li>
          <li class="divider"></li>
          <li><%= link_to 'Logout', logout_path(current_user) %></li>
        </ul>
      </li>
      <% else %>
      <ul class="menu">
        <li><a href="#" data-reveal-id="login">LOGIN</a></li>
        <li><a href="#" data-reveal-id="signup">SIGNUP</a></li>
      </ul>
      <% end %>
    </ul>
    <div id="login" class="reveal-modal" data-reveal>
      <%= render 'layouts/login' %>
      <a class="close-reveal-modal">&#215;</a>
    </div>

    <div id="signup" class="reveal-modal" data-reveal>
      <%= render 'layouts/signup' %>
      <a class="close-reveal-modal">&#215;</a>
    </div>
  </section>
</nav>

<div id="search-form" data-dropdown-content class="f-dropdown content small" aria-hidden="true" tabindex="-1">
  <%= form_tag stories_search_path, :method => :get do %>
  <%= text_field_tag :search, params[:search], :placeholder => "search for stories" %>
  <p align="right"><%= submit_tag "Search", :name => nil, class: "button radius", id: 'search-button' %></p>
  <% end %> </div>

app/views/layouts/_signup.html.erb
  <%= form_for(:user, url: signup_path) do |f| %>
        <fieldset>
          <legend>Signup</legend>
            <%= f.label :username %>
            <%= f.text_field :username %>
            <%= f.label :email %>
            <%= f.text_field :email %>
            <%= f.label :password %>
            <%= f.password_field :password %>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
            <%= f.submit "Sign Up", :class => "button secondary expand" %>
        </fieldset>
      <% end %>

app/views/layouts/_signupsidebar.html.erb
    <%= form_for(:user, url: signup_path) do |f| %>
          <fieldset>
            <legend>Signup</legend>
              <%= f.label :username %>
              <%= f.text_field :username %>
              <%= f.label :email %>
              <%= f.text_field :email %>
              <%= f.label :password %>
              <%= f.password_field :password %>
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation %>
              <%= f.submit "Sign Up" %>
          </fieldset>
        <% end %>

app/views/layouts/_usersidebar.html.erb
User side bar
 hello, <div class="logged-in-user"><%= current_user.first_name %></div>

 hello, <%= current_user.first_name %>


 <h5>Here are your unpublished posts:</h5>
   <% current_user.all_unpublished.each do |story| %>
      <p><%=link_to story.title, story_path(story) %></p>
    <% end %>

 <h5>Some of your published work:</h5>
   <% current_user.all_published.each do |story| %>
      <p><%= link_to story.title, story_path(story) %></p>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Story Vine" %></title>
    <link href='http://fonts.googleapis.com/css?family=Bitter:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Karla:400,700,700italic,400italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div id="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>


    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>